Update kintParser.class.php
I was receiving the following PHP errors after activating the plugin in my local dev environment because I have PHP version 8.0.1 installed:

========================================================

Fatal error: Array and string offset access syntax with curly braces is no longer supported in "Site/app/public/wp-content/plugins/UpDevTools/vendor/kint-php/kint/inc/kintParser.class.php"

========================================================

I simply updated lines 463 and 465 to use brackets instead of curly braces.